//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAngularSample.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DegreeRequirement
    {
        public int RequirementId { get; set; }
        public int DegreeId { get; set; }
        public string ClassStandingCode { get; set; }
        public string SessionCode { get; set; }
        public string DepartmentCode { get; set; }
        public int CourseNumber { get; set; }
    
        public virtual ClassStanding ClassStanding { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual Degree Degree { get; set; }
        public virtual Session Session { get; set; }
    }
}
